// AIAssistModal.tsx
import { useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

type ToolKey = 'summary' | 'custom'

const meta: Record<ToolKey, { icon: string; label: string }> = {
  summary: { icon: 'ti-file-text', label: 'Content Summary' },
  custom: { icon: 'ti-sparkles', label: 'AI Assistant' },
}

interface AIAssistModalProps {
  toolKey: ToolKey | null
  result: string
  dark: boolean
  onClose: () => void
  onApply?: (result: string) => void
}

export const AIAssistModal = ({ toolKey, result, dark, onClose, onApply }: AIAssistModalProps) => {
  useEffect(() => {
    document.body.style.overflow = toolKey ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [toolKey])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [onClose])

  const currentMeta = toolKey ? meta[toolKey] : null

  return (
    <AnimatePresence>
      {toolKey && currentMeta && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-50"
            style={{ backdropFilter: 'blur(8px)', backgroundColor: 'rgba(0,0,0,0.5)' }}
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 16 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 16 }}
            transition={{ type: 'spring', stiffness: 380, damping: 30 }}
            className={`fixed z-50 inset-x-4 top-[10%] mx-auto max-w-xl rounded-2xl border overflow-hidden
              ${dark ? 'bg-[#27272A] border-gray-800' : 'bg-white border-gray-100'}`}
          >
            {/* Header */}
            <div className={`flex items-center gap-3 px-5 py-4 border-b ${dark ? 'border-gray-800' : 'border-gray-100'}`}>
              <div className="w-8 h-8 rounded-lg flex items-center justify-center bg-blue-50 flex-shrink-0">
                <i className={`ti ${currentMeta.icon}`} style={{ fontSize: 16, color: '#2563EB' }} aria-hidden />
              </div>
              <div className="flex-1">
                <p className={`text-sm font-medium ${dark ? 'text-white' : 'text-gray-900'}`}>{currentMeta.label}</p>
                <p className={`text-xs ${dark ? 'text-gray-500' : 'text-gray-400'}`}>Generated by AI · just now</p>
              </div>
              <button
                onClick={onClose}
                className={`w-8 h-8 flex items-center justify-center rounded-full transition-colors
                  ${dark ? 'hover:bg-gray-800 text-gray-400' : 'hover:bg-gray-100 text-gray-500'}`}
              >
                <i className="ti ti-x" style={{ fontSize: 15 }} />
              </button>
            </div>

            {/* Body */}
            <div className={`px-5 py-4 max-h-[55vh] overflow-y-auto text-sm leading-relaxed whitespace-pre-line chat-scroll-dark
              ${dark ? 'text-gray-300' : 'text-gray-700'}`}>
              {result}
            </div>

            {/* Footer */}
            <div className={`flex items-center justify-between px-5 py-3 border-t ${dark ? 'border-gray-800' : 'border-gray-100'}`}>
              <p className={`text-xs ${dark ? 'text-gray-600' : 'text-gray-400'}`}>
                AI can make mistakes — review before publishing.
              </p>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => navigator.clipboard.writeText(result)}
                  className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border transition-colors
                    ${dark ? 'border-gray-700 text-gray-400 hover:bg-gray-800' : 'border-gray-200 text-gray-500 hover:bg-gray-50'}`}
                >
                  <i className="ti ti-copy" style={{ fontSize: 12 }} />
                  Copy
                </button>
                {onApply && (
                  <button
                    onClick={() => { onApply(result); onClose() }}
                    className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg bg-[#2563EB] text-white hover:bg-blue-700 transition-colors"
                  >
                    <i className="ti ti-check" style={{ fontSize: 12 }} />
                    Apply
                  </button>
                )}
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}