// AIAssistModal.tsx
// Shared modal for all AI results in NewPost

import { useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

const SIMULATED: Record<string, string> = {
  generateTitle: `Here are 5 title suggestions:\n\n1. "Building Scalable Systems: A Practical Guide"\n2. "The Modern Developer's Playbook"\n3. "From Zero to Production: Architecture That Works"\n4. "Clean Code, Clean Architecture"\n5. "The Backend Engineer's Field Manual"`,
  improveDesc:   `Improved description:\n\n"A hands-on guide to building production-ready systems — covering architecture patterns, performance optimization, and the tooling modern teams rely on."`,
  grammar:       `Grammar check complete. Found 3 suggestions:\n\n• "its" → "it's" (paragraph 2)\n• "alot" → "a lot" (paragraph 4)\n• Missing comma after introductory clause in paragraph 6.`,
  rewrite:       `Here's a rewritten version with improved clarity and flow:\n\nLorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis — tempus leo eu aenean sed diam urna tempor.`,
  expand:        `Here's an expanded version with additional context and examples:\n\nLorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat.\n\nIn id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere.`,
  shorten:       `Here's a more concise version:\n\nLorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem.`,
  tone:          `Tone variants:\n\n**Professional:** "This comprehensive analysis demonstrates..."\n**Conversational:** "Here's the thing about..."\n**Technical:** "The implementation leverages..."`,
}

const TOOL_LABEL: Record<string, { label: string; icon: string }> = {
  generateTitle: { label: 'Title suggestions',    icon: 'ti-heading' },
  improveDesc:   { label: 'Improved description', icon: 'ti-pencil' },
  grammar:       { label: 'Grammar check',        icon: 'ti-check' },
  rewrite:       { label: 'Rewrite',              icon: 'ti-refresh' },
  expand:        { label: 'Expand content',       icon: 'ti-arrows-maximize' },
  shorten:       { label: 'Shorten content',      icon: 'ti-arrows-minimize' },
  tone:          { label: 'Tone suggestions',     icon: 'ti-mood-smile' },
}

interface AIAssistModalProps {
  toolKey: string | null
  dark: boolean
  onClose: () => void
  onApply?: (result: string) => void
}

export const AIAssistModal = ({ toolKey, dark, onClose, onApply }: AIAssistModalProps) => {
  const meta = toolKey ? TOOL_LABEL[toolKey] : null
  const result = toolKey ? SIMULATED[toolKey] ?? '' : ''

  useEffect(() => {
    document.body.style.overflow = toolKey ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [toolKey])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [onClose])

  return (
    <AnimatePresence>
      {toolKey && meta && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-50"
            style={{ backdropFilter: 'blur(8px)', backgroundColor: 'rgba(0,0,0,0.5)' }}
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 16 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 16 }}
            transition={{ type: 'spring', stiffness: 380, damping: 30 }}
            className={`fixed z-50 inset-x-4 top-[10%] mx-auto max-w-xl rounded-2xl border overflow-hidden
              ${dark ? 'bg-[#27272A] border-gray-800' : 'bg-white border-gray-100'}`}
          >
            {/* Header */}
            <div className={`flex items-center gap-3 px-5 py-4 border-b ${dark ? 'border-gray-800' : 'border-gray-100'}`}>
              <div className="w-8 h-8 rounded-lg flex items-center justify-center bg-blue-50 flex-shrink-0">
                <i className={`ti ${meta.icon}`} style={{ fontSize: 16, color: '#2563EB' }} aria-hidden />
              </div>
              <div className="flex-1">
                <p className={`text-sm font-medium ${dark ? 'text-white' : 'text-gray-900'}`}>{meta.label}</p>
                <p className={`text-xs ${dark ? 'text-gray-500' : 'text-gray-400'}`}>Generated by AI · just now</p>
              </div>
              <button
                onClick={onClose}
                className={`w-8 h-8 flex items-center justify-center rounded-full transition-colors
                  ${dark ? 'hover:bg-gray-800 text-gray-400' : 'hover:bg-gray-100 text-gray-500'}`}
              >
                <i className="ti ti-x" style={{ fontSize: 15 }} />
              </button>
            </div>

            {/* Body */}
            <div className={`px-5 py-4 max-h-[55vh] overflow-y-auto text-sm leading-relaxed whitespace-pre-line chat-scroll-dark
              ${dark ? 'text-gray-300' : 'text-gray-700'}`}>
              {result}
            </div>

            {/* Footer */}
            <div className={`flex items-center justify-between px-5 py-3 border-t ${dark ? 'border-gray-800' : 'border-gray-100'}`}>
              <p className={`text-xs ${dark ? 'text-gray-600' : 'text-gray-400'}`}>
                AI can make mistakes — review before publishing.
              </p>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => navigator.clipboard.writeText(result)}
                  className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border transition-colors
                    ${dark ? 'border-gray-700 text-gray-400 hover:bg-gray-800' : 'border-gray-200 text-gray-500 hover:bg-gray-50'}`}
                >
                  <i className="ti ti-copy" style={{ fontSize: 12 }} />
                  Copy
                </button>
                {onApply && (
                  <button
                    onClick={() => { onApply(result); onClose() }}
                    className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg bg-[#2563EB] text-white hover:bg-blue-700 transition-colors"
                  >
                    <i className="ti ti-check" style={{ fontSize: 12 }} />
                    Apply
                  </button>
                )}
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}