export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_ONE_USER = 'GET_ONE_USER';
export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS';
export const GET_ONE_USER_ERROR = 'GET_ONE_USER_ERROR';

export const GET_ALL_CARTEGORIES = 'GET_ALL_CARTEGORIES';
export const GET_ALL_CARTEGORIES_SUCCESS = 'GET_ALL_CARTEGORIES_SUCCESS';
export const GET_ALL_CARTEGORIES_ERROR = 'GET_ALL_CARTEGORIES_ERROR';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR';

export const GET_ONE_POST = 'GET_ONE_POST';
export const GET_ONE_POST_SUCCESS = 'GET_ONE_POST_SUCCESS';
export const GET_ONE_POST_ERROR = 'GET_ONE_POST_ERROR';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const RESET_STATE_POST = 'RESET_STATE_POST';